fix viewmodel type in viewmodel after changing global address in db to string
radixdlt/babylon-gateway pull request #139
Opened 2023-02-03 13:17 UTC by PawelPawelec-RDX

2023-02-03 13:42 UTC, KrzysztofLabus-RDX approved these changes
Approving but shouldn't we immediately switch to `GlobalAddress` rather `string`?

2023-02-03 14:22 UTC, PawelPawelec-RDX commented
> Approving but shouldn't we immediately switch to `GlobalAddress` rather `string`?

@KrzysztofLabus-RDX good idea, created custom mapper.

2023-02-03 15:29 UTC, KrzysztofLabus-RDX requested changes

2023-02-03 15:29 UTC, KrzysztofLabus-RDX commented on src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.cs
> +    private record FungiblesViewModel(GlobalAddress? ResourceEntityGlobalAddress, string Balance, int TotalCount);
Those can't be null?

2023-02-06 09:54 UTC, KrzysztofLabus-RDX approved these changes

2023-02-06 10:01 UTC, merged