event global emitter filter.
radixdlt/babylon-gateway pull request #766
Opened 2024-07-12 15:04 UTC by PawelPawelec-RDX

2024-07-15 14:07 UTC, krzlabrdx requested changes

2024-07-15 14:07 UTC, krzlabrdx commented on src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/AffectedGlobalEntitiesProcessor.cs
> +            .ToList();
Hint: we don't need to `.ToList()` everything. ;-)

2024-07-15 14:07 UTC, krzlabrdx commented on src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/GlobalEventEmitterProcessor.cs
> +        if (!_globalEventEmitters.TryGetValue(stateVersion, out var list))
ditto (`.GetOrAdd`)

2024-07-15 14:07 UTC, krzlabrdx commented on src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/PostgresLedgerExtenderService.cs
> +            ledgerTransactionMarkersToAdd.AddRange(affectedGlobalEntitiesProcessor.CreateTransactionMarkers());
Hint: those method could possibly benefit from becoming generators (`IEnumerable<TxMarker>` return type + `yield return`s) - fewer allocations and arguably more readable code.

2024-07-16 07:50 UTC, PawelPawelec-RDX commented on src/RadixDlt.NetworkGateway.PostgresIntegration/LedgerExtension/AffectedGlobalEntitiesProcessor.cs
> +        list.Add(new(entityId, entityType));
you're right it can be removed. I was initialy filtering out on entity type but that didn't handle internal entities properly.

2024-07-16 10:46 UTC, krzlabrdx approved these changes

2024-07-16 12:10 UTC, merged